Q1. Assign your Name to variable name and Age to variable age. Make a Python program that prints your name and age.

In [2]:
var = 'MANBIR KAUR'
var

'MANBIR KAUR'

In [4]:
var1 = 20
var1

20

In [13]:
print('My name is',var,'and my age is', var1,'.')

My name is MANBIR KAUR and my age is 20 .


Q2. X="Datascience is used to extract meaningful insights."
Split the string

In [1]:
X="Datascience is used to extract meaningful insights."
X

'Datascience is used to extract meaningful insights.'

In [2]:
X.split()

['Datascience', 'is', 'used', 'to', 'extract', 'meaningful', 'insights.']

Q3. Make a function that gives multiplication of two numbers.

In [3]:
num1=12
num2=2
num3 = num1 * num2
num3

24

Q4. Create a Dictionary of 5 States with their capitals. also print the keys and values.


In [6]:
Dictionary = {'States':['Madhya Pradesh','Maharashtra','Rajasthan','Tamil Nadu','Uttarakhand'],'Capital':['Bhopal','Mumbai','Jaipur','Chennai','Dehradun']}


In [7]:
print(Dictionary)

{'States': ['Madhya Pradesh', 'Maharashtra', 'Rajasthan', 'Tamil Nadu', 'Uttarakhand'], 'Capital': ['Bhopal', 'Mumbai', 'Jaipur', 'Chennai', 'Dehradun']}


In [8]:
Dictionary.keys()

dict_keys(['States', 'Capital'])

In [9]:
Dictionary.values()

dict_values([['Madhya Pradesh', 'Maharashtra', 'Rajasthan', 'Tamil Nadu', 'Uttarakhand'], ['Bhopal', 'Mumbai', 'Jaipur', 'Chennai', 'Dehradun']])

Q5. Create a list of 1000 numbers using range function.


In [20]:
import numpy as np
np.arange(start = 1, stop = 1001)


array([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
         23,   24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
         34,   35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
         45,   46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
         56,   57,   58,   59,   60,   61,   62,   63,   64,   65,   66,
         67,   68,   69,   70,   71,   72,   73,   74,   75,   76,   77,
         78,   79,   80,   81,   82,   83,   84,   85,   86,   87,   88,
         89,   90,   91,   92,   93,   94,   95,   96,   97,   98,   99,
        100,  101,  102,  103,  104,  105,  106,  107,  108,  109,  110,
        111,  112,  113,  114,  115,  116,  117,  118,  119,  120,  121,
        122,  123,  124,  125,  126,  127,  128,  129,  130,  131,  132,
        133,  134,  135,  136,  137,  138,  139,  140,  141,  142,  143,
        144,  145,  146,  147,  148,  149,  150,  1

Q6. Create an identity matrix of dimension 4 by 4.

In [33]:
import numpy as np
m = np.eye(4)

In [34]:
m

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Q7. Create a 3x3 matrix with values ranging from 1 to 9

In [32]:
import numpy as np
r = np.arange(1,10).reshape(3,3)
r

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Q8.Create 2 similar dimensional array and perform sum on them.

In [37]:
arr1 = np.arange(0,11,3)
arr1.ndim

1

In [43]:
arr2 = np.arange(2,13,3)
arr2.ndim

1

In [39]:
arr1

array([0, 3, 6, 9])

In [44]:
arr2

array([ 2,  5,  8, 11])

In [45]:
arr3 = np.add(arr1,arr2)
arr3

array([ 2,  8, 14, 20])

Q9. Generate the series of dates from 1st Feb, 2023 to 1st March, 2023 (both inclusive)

In [48]:
import pandas as pd
dRan1 = pd.date_range(start ='2-1-2023', end ='3-1-2023', freq ='24H')
print(dRan1)

DatetimeIndex(['2023-02-01', '2023-02-02', '2023-02-03', '2023-02-04',
               '2023-02-05', '2023-02-06', '2023-02-07', '2023-02-08',
               '2023-02-09', '2023-02-10', '2023-02-11', '2023-02-12',
               '2023-02-13', '2023-02-14', '2023-02-15', '2023-02-16',
               '2023-02-17', '2023-02-18', '2023-02-19', '2023-02-20',
               '2023-02-21', '2023-02-22', '2023-02-23', '2023-02-24',
               '2023-02-25', '2023-02-26', '2023-02-27', '2023-02-28',
               '2023-03-01'],
              dtype='datetime64[ns]', freq='24H')


Q10. Given a dictionary, convert it into corresponding dataframe and display it
dictionary = {'Brand': ['Maruti', 'Renault', 'Hyndai'], 'Sales' : [250, 200, 240]}

In [49]:
dic =  {'Brand': ['Maruti', 'Renault', 'Hyndai'], 'Sales' : [250, 200, 240]}
dic

{'Brand': ['Maruti', 'Renault', 'Hyndai'], 'Sales': [250, 200, 240]}

In [50]:
type(dic)

dict

In [54]:
dic = pd.DataFrame(dic)
dic

Brand  Sales
0   Maruti    250
1  Renault    200
2   Hyndai    240